### PR TITLE
support for ES compatible DSL in .count

### PR DESCRIPTION
**Pull request by slorf**
add support for ES compatible DSL in .count through 'where.native' key

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by pulkitsinghal** [comment]
Seems reasonable, @slorf: just for sanity's sake, is it safe to assume you've ran this code once and used it?

**Comment by slorf** [comment]
Yes, I have.
Thank you for the swift response.

**Comment by pulkitsinghal** [comment]
I'm having second thoughts about these changes:
```
    var body = where.native ? where.native : {
        query: self.buildWhere(modelName, idName, where).query
    };
```

Why wasn't `buildWhere().query` which performed:
```
        else if (criteria.native) {
            filter.body = criteria.native; // assume that the developer has provided ES compatible DSL
        }
```
sufficient? What was it returning that was a mismatch?

I will think on it more and report back here what I concluded and if any changes will be coming soon.

**Comment by slorf** [comment]
buildWhere always adds the body-key to query, which is not required in _count

**Pull request merged**
