### PR TITLE
Setup Travis CI

### PR DESCRIPTION
**Pull request by bajtos**
Configure Travis CI to provide feedback on pull requests.

cc @pulkitsinghal

### CODE REVIEW

**Comment by bajtos** [comment]
@pulkitsinghal AFAICT, the tests use hard-coded connection config specified in https://github.com/strongloop-community/loopback-connector-elastic-search/blob/b773ec0bf04abe0fa308dfb2f5f58a523b493c8c/test/resource/datasource-test.json#L5-L12:

```
            "protocol": "https",
            "host": "hosted.foundcluster.com",
            "port": 9243,
            "auth": "username:password"
```

As a result, the test suite does not connect to the local ElasticSearch instance provided by Travis.

I am suggesting to rework datasource setup to make it easy to configure the target ES server used by tests, without having to changing any code. For example, the test setup can use env variables to configure the connection. 

If needed, I can add ENV variables to Travis configuration for you, as needed.

Having wrote that, I am afraid I don't have any more bandwidth to help with setting up the CI, and will leave this pull request in the hands of maintainers of this project.

**Comment by pulkitsinghal** [comment]
@bajtos - i was able to reach acceptable test quality metrics for my sanity via the docker implementation added by @harshadyeola in https://github.com/strongloop-community/loopback-connector-elastic-search/pull/42 so I'll table this for now.

Thank you for your help, I'm not closing this, I will make time for this again at a later date.

**Comment by bajtos** [comment]
@pulkitsinghal thank you for the comment, I totally understand you!

**Comment by bajtos** [comment]
As part cleaning up my backlog, I am going to close this pull request as abandoned.

**Pull request closed without merging**
