### PR TITLE
Added phrase search support. Fixed the query issue of OR inside and AND for where filter. 

### PR DESCRIPTION
**Pull request by AhsanAyaz**
Fixed the query issue of OR inside and AND for where filter.
Wrote the filter test for above case since it was missing.
Added support for querying phrases. Wrote a filter test for that too.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by AhsanAyaz** [comment]
Fixes #93

**Comment by AhsanAyaz** [comment]
Did anyone get a chance to review the PR?

**Comment by AhsanAyaz** [comment]
@pulkitsinghal I've rebased my PR with your repository so there shouldn't be any conflicts left. 

Thanks.

**Comment by pulkitsinghal** [comment]
> @pulkitsinghal I've rebased my PR with your repository so there shouldn't be any conflicts left.

Thanks @AhsanAyaz, I appreciate your help! I didn't notice your comment until just now so in the meantime I used the manual approach:
```
git checkout -b AhsanAyaz-develop develop
git pull git://github.com/AhsanAyaz/loopback-connector-elastic-search.git develop
```
to do the same locally.

Here are the changes I made:
1. removed the phrase search support because that's what `native` is for:
    * Sample usage/test: https://github.com/strongloop-community/loopback-connector-elastic-search/blob/11ad3f789b70709d17c2bf5096397321fee0e210/test/es-v1/01.filters.test.js#L79
    * Implementation: https://github.com/strongloop-community/loopback-connector-elastic-search/blob/11ad3f789b70709d17c2bf5096397321fee0e210/lib/esConnector.js#L991
    * Why do it this way and not support the way you are recommending? Because I want more feedback from the community on how to support all the ES specific keywords in the connector before just plugging them in. Right now I like playing it safe and only providing keywords from the loopback's pseudo-ORM. Feel free to open a new PR for `Added phrase search support`
2. I removed the mix of `tabs` and `whitespaces` then fixed the indentations
3. I ran the test against ES version 1.x:
    ```
    docker-compose -f docker-compose-for-testing-v1.yml up
    npm run testv1
    ```
4. Now I'm planning to copy over the test for all versions, which yes is a bit wasteful until I become more clever about managing tests.

**Comment by pulkitsinghal** [comment]
https://github.com/strongloop-community/loopback-connector-elastic-search/pull/100 Has been merged into `develop` but hasn't been released.

@AhsanAyaz - do you want to take this chance to close this specific PR and then start over from develop for only the `phrase search support` (will require some discussion therefore delays) or are ok with using `native`?

I can plan to release with or without ``phrase search support` as the tests are passing. Let me know.

**Comment by AhsanAyaz** [comment]
@pulkitsinghal I think you're right with the `native` approach. And since it is pretty dynamic, we won't have to put/plug too many of them. I'll modify the approach in my application with `native`. You can proceed  without `phrase search support`. 

Thanks.

**Comment by AhsanAyaz** [comment]
I'm closing this PR as the one without `phrase search support` has already been merged. 
Do let me know your plan to have a `release`. 
Thanks 👍

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by pulkitsinghal** [comment]
fixed and released in v1.4.1 - Jun 6, 2017

**Pull request closed without merging**
