### PR TITLE
Use settings.type for name conversion

### LINKED ISSUE #31: Add mapping for Loopback model name to ES type
We use a domain-specific model name for our loopback model but we cannot change the ES url (it's a 3rd party server install). It would be helpful to map loopback model name to ES type in URLs.

For example, we want to map our Customer model to an ES url like /index/user.  Customer -> user

### PR DESCRIPTION
**Pull request by lukewendling**
fix #31 quickly and dirty-ly

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by endjay** [comment]
great i need this too , is this all ready patch and update on npm package  ?

**Comment by lukewendling** [comment]
@endjay I don't know but I'm using my github fork, specified in package.json

**Comment by pulkitsinghal** [comment]
@lukewendling and @endjay - thanks for the wake up call, I published version `1.0.3` with these changes to NPM now

**Comment by pulkitsinghal** [comment]
@lukewendling - I don't think I heard back from you about my feedback i nthe gitter chat room back when:
> Nov 18 14:20
@lukewendling - not sure the fix you made thus far is the right one ... did it actually work for you? the way you have it, i think you'll end up with one custom type for all models instead of one custom type per model

**Comment by lukewendling** [comment]
@pulkitsinghal this was definitely a quick fix. it allows to create an ES connector for each specified type. thus one config section in datasources.json for each type. not ideal. a better solution perhaps is a mapping from model name to ES type, perhaps in datasources.json.

**Pull request merged**
