### PR TITLE
Support Signed Requests for AWS Elasticsearch-Service

### PR DESCRIPTION
**Pull request by dtomasi**
I´m using AWS Elasticsearch-Service and wasn´t able to connect. So I had to sign the requests. Thinking this could also be interesting for someone else who uses AWS.

Best regards
Dominik

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by pulkitsinghal** [comment]
Looks simple enough. Would it be more prudent to somehow make the addition of the amazon dependency documented for those who want this rather than increasing the size of installed dependencies by default for everyone?

**Comment by dtomasi** [comment]
I agree! It´s really not necessary to increase the number of dependencies.

**Comment by pulkitsinghal** [comment]
@dtomasi - thank you for this:
> changed the base branch to strongloop-community:develop from strongloop-community:master

**Pull request merged**
