### PR TITLE
updating elastich search packages to the latest

### PR DESCRIPTION
**Pull request by jonaskac**
This solves the issue with an infinite loop in log.js:68

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by arnaudsj** [comment]
Please merge this ASAP. I tested it and it works.

**Comment by pulkitsinghal** [comment]
.ok\W+to\W+test.

**Comment by pulkitsinghal** [comment]
doesn't seem to have merged :(

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Pull request merged**
