### PR TITLE
Upgrade Elasticsearch client to 14.0.0

### PR DESCRIPTION
**Pull request by sbmthakur**
I've updated the Elasticsearch client to `14.0.0` as it supports ES 6 API. The upgraded client worked properly with previous Elastic versions. I'm also working on support for ES 6. I'll add the tests for the same in successive commits.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by pulkitsinghal** [comment]
thank you @sbmthakur i will wait for tests

cc @caiyufei

**Comment by prateekrastogi** [comment]
Any updates on the merging of pull request to support api version 6.1?

**Comment by pulkitsinghal** [comment]
There are huge changes in ES v6 and some folks like @bharathkontham are well on their way to changing the connector in a workable fashion. But without tests I have two options:

1. Redirect folks to use https://github.com/bharathkontham/loopback-connector-elastic-search within their package.json when they wan to work with ES v6
2. Request that @rmg or @bajtos add folks like bharathkontham here as a contributor so they may actively help maintain this repo

if the changes from `bharathkontham/loopback-connector-elastic-search` get merged as-is then we might(?) be not be ale to use previous versions of ES so some thought needs to go into how to:
a. keep the same code base while supporting all flavors
b. separate the codebase and publish different packages for each es version

**Comment by pulkitsinghal** [comment]
a quick copy/paste/edit of the tests for v6 shows we need to do more work

So `bharathkontham/loopback-connector-elastic-search`'s fork  is probably the best bet for those who want to work with ES v6.x until we can agree to host a conference call (google hangouts) with some interested parties volunteering to discuss everyone's ideas and to hash out how we want to proceed forward.

**Comment by sbmthakur** [comment]
Hello guys, due to busy schedule I could not finish the tests yet. I'll be working on them over the weekend. Thank you for your patience.

**Comment by bajtos** [comment]
> Request that @rmg or @bajtos add folks like bharathkontham as a contributor to this repo so they may actively help maintain this repo


@pulkitsinghal I personally consider you as the main maintainer of this project. If you think we should add @bharathkontham as a contributor then I am fine with that. Should I do it right now?

**Comment by prateekrastogi** [comment]
@pulkitsinghal  Thanks for the information. I have started using @bharathkontham work by directly pulling from his git repo. But, please do keep us updated about the future course of action .

**Comment by pulkitsinghal** [comment]
Yes @bajtos, please add @bharathkontham as a contributor

**Comment by pulkitsinghal** [comment]
@bharathkontham - treat feature/esv6 as your "develop" ... create feature/esv6/featurename branches from it and PR/merge them back to feature/esv6 and the releases branches can be used to publish the package under the name loopback-connector-esv6 on npmjs

**Comment by bajtos** [comment]
@pulkitsinghal 
> please add @bharathkontham as a contributor

done (invitation sent)

**Comment by pulkitsinghal** [comment]
thank you @bajtos

**Pull request closed without merging**
